### ISSUE TITLE
Audit countries whose names don't match between world.json file and dynamodb 

### ISSUE THREAD

**Issue by AaronHaNasi** [AaronHaNasi/team-civil-discourse#59]
- What countries are in the Google Doc and not displaying correctly, what is the name associated with them in the _world.json_? Make a list of all the countries where this applies.
- Add this _world.json_ name as an alias to the country information stored in DynamoDB.
- Update ColorMap.js functions to check country['CountryAliases'] as a list, and if it contains the string name that was given to the function, then yeet

**Notes**
It's a large file so a specialty text editor might be needed.

world.json is located in /team-civil-discourse/client/src/geoJson/world.json

**Comment by 17kisern** [comment]
Just adding the text file that Nick put together as a comment
[country_namelist.txt](https://github.com/AaronHaNasi/team-civil-discourse/files/6145141/country_namelist.txt)
